### PR TITLE
Fixed L.multiPolyline/gon For Leaflet 1.0

### LINKED ISSUE #95: MULTIPOLYGON creation not working in Leaflet 1.0
With the release of Leaflet 1.0, L.multiPolygon is no longer a function, and therefore an error is thrown when Wicket is parsing a MULTIPOLYGON (L.multiPolygon is not a function). 

It appears the new way to create a Multipolygon is to pass a multidimensional array to L.polygon (http://leafletjs.com/reference-1.0.0.html#polygon).

### PR DESCRIPTION
**Pull request by crash-dive**
Fixes #95

### CODE REVIEW

**Comment by arthur-e** [comment]
Great, thanks!
